### ISSUE TITLE
.air: No such file or directory

### ISSUE THREAD

**Issue by mytc** [cosmtrek/air#103]
Hi, I got this error :
`.air: No such file or directory
`

The go version is go version go1.14.6 linux/amd64
I followed your readme guide to install the package.
Here is my .bashrc 
```
export GOPATH=$HOME/gopro
export PATH=$PATH:$GOPATH/bin
alias air='~/.air'
```
And I have `source .bashrc` after edit the file, But still not working. 

Any idea?
Thanks.

**Comment by xiantang** [comment]
you can try to remove `alias air='~/.air'` from your .bashrc
because if you run air it will execute air in you home path, and air absolutely not in your home path.
and you can try add `export PATH=$PATH:$(go env GOPATH)/bin` below `export PATH=$PATH:$GOPATH/bin`
and source your `.bashrc` again.
@mytc

**Comment by mytc** [comment]
@xiantang still not working. 
Maybe it is becuase I am using gvm?

**Comment by mytc** [comment]
@xiantang Ok. working now!! Thanks.
