### ISSUE TITLE
watch multiple dirs

### ISSUE THREAD

**Issue by adamleo** [cosmtrek/air#23]
Hey @cosmtrek ,

Thanks for this awesome tool.
Just wondering that is there any support on watching multiple directories atm? I couldn't find any.
Or is there any plan to add this feature in the future?
Would be really helpful.

Cheers.

**Comment by cosmtrek** [comment]
It can watch current directories and subdirectories atm. Could you give me an example?

**Comment by jasonw-rr** [comment]
I am having the same wondering here too.

For example:
```
root_dir
  |- common
       |- business_lifecycle
  |- models
       |- model_1
       |- model_2
  |- service_1
  |- service_2
```
So different team focus on different service development.
Say, I am team 1. 
I wish to hot reload when there is a change to `/common`, `/models`, and `service_1`, but NOT `service_2`

**Comment by stanleynguyen** [comment]
hey @jasonw-rr you can do 
```toml
root="root_dir"
exclude_dir = ["service_2"]
```

**Comment by jasonw-rr** [comment]
> hey @jasonw-rr you can do
> 
> ```toml
> root="root_dir"
> exclude_dir = ["service_2"]
> ```

@stanleynguyen thanks for replying.
I guess it is more of a nice-to-have request.
Of course I could do it the way you suggested, but it's not really intuitive and not self-explanatory  of what's required.

In a more complicated repository, there would be 6+ services. 
If a new sub directory is introduced by, say service_6, and is only used by service_6, instead of adding another directory to monitor in air.conf of service_6, you need to add the exclusion in service 1~5.

**Comment by cosmtrek** [comment]
@jasonw-rr @adamleo I've finished the [`include_dir`](https://github.com/cosmtrek/air/commit/3409634cf6466a9b34de35a507e76a66ac5d87fe) feature. 

The config may like this:
```
root = "."
include_dir = ["common", "models", "service_1"]
```

**Comment by adamleo** [comment]
thanks, i'll close this now.

**Comment by jasonw-rr** [comment]
Highly appreciated 🙏🏻
