### ISSUE TITLE
`air -v` not showing version when installed with `go install`

### ISSUE THREAD

**Issue by roeniss** [cosmtrek/air#432]
Hi! The air and go versions are not shown on `air -v` on my computer.

- `git clone https://github.com/cosmtrek/air && cd air && make install && air -v` → shows versions well
- `go install github.com/cosmtrek/air@latest && air -v` → don't show versions well

```
> go install github.com/cosmtrek/air@v1.43.0
go: downloading github.com/cosmtrek/air v1.43.0
> air -v

  __    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ , built with Go 

> trash air
> go install github.com/cosmtrek/air@latest
> air -v

  __    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ , built with Go 
```

I'm on:

- macOS 13.3.1 (m1; aarch64)
- kernel: 22.4.0
- zsh 5.9

```
> sha256sum air
47c333b9cf61cdaa5b9aab19892c9d452204a58f5abdda6364a4aae9c3a3c164  air
```

I'm wondering this is known issue.

**Comment by gaols** [comment]
I think there is a bug. The airVersion used to bind ldflags is not exported, so I created a pull request [#433](https://github.com/cosmtrek/air/pull/433).

**Comment by makiuchi-d** [comment]
The reason is that `go install` does not call `make`.
It does not matter if the variable is exported or not.

It should use [debug.BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo), like this: [makiuchi-d/arelo/arelo.go#L137-L141](https://github.com/makiuchi-d/arelo/blob/e2a33c2eabee0c662ead2890bdfc4652465e6192/arelo.go#L137-L141)

**Comment by xiantang** [comment]
![image](https://github.com/cosmtrek/air/assets/34479567/c3cdfc43-613e-4367-8683-34dc124d3253)
 fixed

**Comment by roeniss** [comment]
nice work!
